# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Chats',
                'ordering': ['active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.Chat')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'verbose_name': 'Message',
                'ordering': ['-creation_timestamp'],
            },
        ),
    ]
