# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0002_auto_20160520_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatsonMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('vote_correct', models.IntegerField(default=0, verbose_name='Vote count: correct')),
                ('vote_incorrect', models.IntegerField(default=0, verbose_name='Vote count: incorrect')),
                ('vote_helpful', models.IntegerField(default=0, verbose_name='Vote count: helpful')),
                ('vote_not_helpful', models.IntegerField(default=0, verbose_name='Vote count: not helpful')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.Chat')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='watson_anwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwb.WatsonMessage'),
        ),
    ]
