# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0003_auto_20160527_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watsonmessage',
            options={'ordering': ['creation_timestamp'], 'verbose_name': 'Message by Watson', 'verbose_name_plural': 'Messages by Watson'},
        ),
    ]
