# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0004_auto_20160603_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='watsonmessage',
            name='api_answer',
            field=models.TextField(default='', help_text='This is filled with the answer watson/blumix gave', verbose_name='Raw bluemix answer'),
        ),
    ]
