# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0007_watsonmessage_answerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='watsonmessage',
            name='additional_data',
            field=models.TextField(default='', help_text='This field contains data that can be used to fullfill later requests', verbose_name='Additional data (JSON dump)'),
        ),
    ]
