# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0008_watsonmessage_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watsonmessage',
            name='additional_data',
            field=models.TextField(blank=True, default='', help_text='This field contains data that can be used to fullfill later requests', verbose_name='Additional data (JSON dump)'),
        ),
        migrations.AlterField(
            model_name='watsonmessage',
            name='api_answer',
            field=models.TextField(blank=True, default='', help_text='This is filled with the answer watson/blumix gave', verbose_name='Raw bluemix answer'),
        ),
    ]
