# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0009_auto_20160804_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'KB Entity',
                'verbose_name_plural': 'KB Entities',
            },
        ),
        migrations.CreateModel(
            name='KBFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('facts', models.TextField()),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'KB Fact',
                'verbose_name_plural': 'KB Facts',
            },
        ),
        migrations.CreateModel(
            name='KBFactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'KB Fact Type',
                'verbose_name_plural': 'KB Fact Types',
            },
        ),
        migrations.CreateModel(
            name='KBFactTypeSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pattern', models.TextField()),
                ('fact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.KBFactType')),
            ],
            options={
                'verbose_name': 'KB Fact Type Sentence Pattern',
                'verbose_name_plural': 'KB Fact Type Sentence Patterns',
            },
        ),
        migrations.AddField(
            model_name='kbfact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.KBFactType'),
        ),
        migrations.AddField(
            model_name='kbentity',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.KBFact'),
        ),
    ]
