# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0010_auto_20160812_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecentFunFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.Chat')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.KBFact')),
            ],
            options={
                'verbose_name_plural': 'Recent FunFact for Chats',
                'verbose_name': 'Recent FunFact for Chat',
                'ordering': ['creation_timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='KBFactTypeSentence',
            new_name='KBFactTypePattern',
        ),
        migrations.AlterModelOptions(
            name='kbfacttypepattern',
            options={'verbose_name': 'KB Fact Type Pattern', 'verbose_name_plural': 'KB Fact Type Patterns'},
        ),
        migrations.RenameField(
            model_name='kbfacttypepattern',
            old_name='pattern',
            new_name='template_text',
        ),
        migrations.AddField(
            model_name='chatrecentfunfacts',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.KBFactTypePattern'),
        ),
    ]
