# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0011_auto_20160814_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRecentFunFacts',
            new_name='ChatRecentFunFact',
        ),
    ]
