# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0012_auto_20160814_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID for cross referencing. May be empty for internal chats', max_length=100, verbose_name='ID of external chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Is external?'),
        ),
    ]
