# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0014_auto_20160909_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbfact',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
