# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0015_kbfact_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watsonmessage',
            name='action_performed',
            field=models.TextField(blank=True, verbose_name='Action(s) performed'),
        ),
        migrations.AddField(
            model_name='watsonmessage',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='watsonmessage',
            name='system_text_post',
            field=models.TextField(blank=True, default='', help_text='System text (to display after the actual message, may contain html tags)'),
        ),
        migrations.AddField(
            model_name='watsonmessage',
            name='system_text_pre',
            field=models.TextField(blank=True, default='', help_text='System text (to display before the actual message, may contain html tags)'),
        ),
    ]
