# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0016_auto_20160925_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatsonProcessingLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('action_performed', models.TextField(blank=True, verbose_name='Action(s) performed')),
                ('stacktrace', models.TextField(blank=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwb.WatsonMessage')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwb.Chat')),
                ('requesting_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bwb.Message')),
            ],
            options={
                'verbose_name': 'Watson Processing Log Entry',
                'verbose_name_plural': 'Watson Processing Log Entries',
                'ordering': ['creation_timestamp'],
            },
        ),
    ]
