# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0017_watsonprocessinglogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watsonprocessinglogentry',
            name='stacktrace',
            field=models.TextField(blank=True, default=''),
        ),
    ]
