# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwb', '0018_auto_20160926_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watsonprocessinglogentry',
            name='stacktrace',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
